### ISSUE TITLE
What does it mean🤔？

### ISSUE THREAD

**Issue by Rabbitzzc** [lukeed/dequal#11]
![image](https://user-images.githubusercontent.com/26913511/89480467-feb59c00-d7c7-11ea-80c5-937bbe128871.png)

I don't quite understand the meaning of this code. Under what circumstances is it needed?

**Comment by lukeed** [comment]
It checks against `NaN` :D 

```js
NaN === NaN;
//=> false
```

Anything else that makes it there (`undefined`, `null`, any truthy value) will pass that check.
It's a weird one, but it's quicker/simpler than checking if `Number.isNaN` or `value % 1 !== 0` for both `foo` and `bar` 

Hope that helps!

**Comment by Rabbitzzc** [comment]
> It checks against `NaN` :D
> 
> ```js
> NaN === NaN;
> //=> false
> ```
> 
> Anything else that makes it there (`undefined`, `null`, any truthy value) will pass that check.
> It's a weird one, but it's quicker/simpler than checking if `Number.isNaN` or `value % 1 !== 0` for both `foo` and `bar`
> 
> Hope that helps!
great!
![image](https://user-images.githubusercontent.com/26913511/89486931-bd78b880-d7d6-11ea-93b2-501779fb576b.png)
