### ISSUE TITLE
Fails when comparing Invalid Date

### ISSUE THREAD

**Issue by wysher** [lukeed/dequal#17]
I tried to use dequal as lodash.isEqual replacement, but find out that when comparing two Invalid Dates dequal returns true.

Not sure if this is correct, because of possible false possitives - new Date('foo') is not same as new Date('bar'). Solution - instead of comparing date.getTime(), isNaN(date) should be considered.

Again, not sure what result to expect here plus changing this will cause BREAKING-CHANGE.

I'll stick with lodash's isEqual for now :(

**Comment by lukeed** [comment]
Closing as duplicate, you double-posted somehow
