### ISSUE TITLE
Extend to compare non-bare objects

### ISSUE THREAD

**Issue by mourner** [lukeed/dequal#4]
Thanks for the great projejct @lukeed! Discovered this while porting a project of mine from `tape` to `uvu` (this was the only blocker):

```js
class Foo {}

const a = new Foo();
const b = new Foo();

dequal(a, b); // false :(
```

I guess this would be fixed by replacing the `ctor === Object` check with `typeof foo === 'object'`. Was this an issue with performance? Comparing class instances and other non-basic objects is indispensable when writing unit tests. 

Related: #2

**Comment by lukeed** [comment]
Hey~! 

I'm pushing up a branch now that should take care of classes. Do you mind checking it out for me & see that it covers your needs?

As for Sets & Maps: I'm saving those for the next major release, as it'll be the introduction of multiple `dequal` modes. It should also be sync'd with `klona`.

Thanks :)

**Comment by mourner** [comment]
@lukeed awesome! It works with that branch ✨

**Comment by lukeed** [comment]
Thanks!
