### ISSUE TITLE
Map and Set Code

### ISSUE THREAD

**Issue by anywhichway** [lukeed/dequal#6]
Here is the code to support Map and Set conventionalized for older browsers (which may not be necessary depending on what you are doing for transpile). I have this locally along with unit test additions. I can do a pull request, you can add to your code, or (of course) you can ignore:

```
if(typeof(Map)==="function" && ctor === Map) {
			if(foo.size === bar.size) {
				for(const [key,value] of foo.entries()) { // Maps are mathematically unordered
					if(!dequal(bar.get(key),value)) { // so ... simple existence of same key value is good enough
						return false;
					}
				}
				return true;
			}
			return false;
		}
		
		if(typeof(Set)==="function" && ctor === Set) {
			if(foo.size === bar.size) {
				for(const fvalue of foo.entries()) { // Sets are mathematically unordered
					let found;
					for(const bvalue of bar.entries()) { // so ... need to compare each entry
						if(found = dequal(fvalue,bvalue)) {
							break;
						}
					}
					if(!found) {
						return false;
					}
				}
				return true;
			}
			return false;
		}
```

**Comment by lukeed** [comment]
Thank you. These will actually throw syntax errors in environments that don't support them.

I have code for these already (and optimized already). It's probably a lame approach, but I have been holding on to it in order to synchronize with `klona`, which admittedly is also mostly done but still had a couple kinks to work out.

**Comment by anywhichway** [comment]
Understand the "witholding" :-)

You mean this will throw an error: `if(typeof(Map)==="function" && ctor === Map) { `? ... or the `const` (which could easily be a `var`)?

**Comment by lukeed** [comment]
Both, but the `ctor === Map/Set` specifically since those globals won't exist in older environments. Is like trying to use `process` in browsers or `window` in Node, for example.

Closing this if you don't mind

**Comment by anywhichway** [comment]
No problem on the close. The ctor should not eval since it is preceeded by the typeof. Although perhaps it should be within the inner scope. Regardless, looking forward to the release of the updated code. I want to provide a option for deepEqual in https://github.com/anywhichway/intersector.

Thanks for such friendly and rapid response to my issues!

**Comment by lukeed** [comment]
Oh sorry. I misread the typeof's -- I thought you had written type checks on the variables not the global constructor. My bad

Aside from that mistake, the rest of my response is still true 😅
